### ISSUE TITLE
Service Intent Must Be Explict

### ISSUE THREAD

**Issue by RegencySoftware** [mobilino/Phonegap-android-license-plugin#3]
When using the plugin the error exception "Service Intent Must Be Explict: Intent {act=com.android.vending.licensing..ILiecnsingSerivice}

**Comment by mobilino** [comment]
Could you give us some more info? When does this error occur and what tools are you using in which version?

**Comment by RegencySoftware** [comment]
Hi mobilino,

I tested this on Samsung S5 with Android 5.  

After the app was fully loaded (ready) I ran the code button using a submit button to test it out.

function checkLic()
{
    AndroidLicensePlugin.check(
    function (data) { alert(JSON.stringify(data)); },
    function (errorString) { alert("error: " + errorString); }
);

[This StackOverflow Link discusses the issue](http://stackoverflow.com/questions/27842430/service-intent-must-be-explicit-intent).

**Comment by mobilino** [comment]
Hi,

are you using the latest version of this plugin? Because WEBoXX commit to this plugin should have removed this bug  https://github.com/mobilino/Phonegap-android-license-plugin/commit/c9d96cc616c1b5b047ba251f5ffbaeb3836dba2a

**Comment by RegencySoftware** [comment]
I was using PhoneGap Build https://build.phonegap.com/plugins/1054 and it must be an old version.

Once I flipped the build over to your repository it worked!

Thank you for creating this plug-in!

**Comment by mobilino** [comment]
thank you!!
